import Logo from './_components/Logo'
import Navigation from './_components/Navigation'
import './_styles/globals.css'

export const metadata = {
	title: 'Rauha',
	description: 'Generated by Next.js',
}

export default function RootLayout({
	children,
}: {
	children: React.ReactNode
}) {
	return (
		<html lang='en'>
			<body
				className='bg-primary-950 text-primary-100  min-h-screen
			'
			>
				<header>
					<Logo />
				</header>
				<Navigation />

				<main>{children}</main>
			</body>
		</html>
	)
}
